### ISSUE TITLE
firemacs breaks arrow keys in google docs

### ISSUE THREAD

**Issue by diekhans** [kazu-yamamoto/Firemacs#18]
If firemacs  is enabled, the arrow keys no longer work in google docs (drive) writer.

Sadly, the emacs key binds don't  work either.

This is a great extension, I wish I didn't have to use google docs.

**Comment by PinkFLoyd92** [comment]
We should have a keybinding to disable firemacs in that page without restarting firefox at least ,so we can use google drive, it is really annoying. I hope you consider fixing this in the future, I really like this addon :(
